version: "3.8"

services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 13306:3306
  app:
    restart: always
    depends_on:
      - db
    build:
      context: ./
    ports:
      - 9090:8080
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
